/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frank
 */
public class statisticsofenrollement extends javax.swing.JFrame {

    /**
     * Creates new form statisticsofenrollement
     */
    public statisticsofenrollement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "MALE", " FEMALE", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        button1.setLabel("CLASS STATISTICS");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("DEPARTMENT STATISTICS");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("CYCLE STATISTICS");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
                                      
Connection con = null;
int cn=0, MC = 0,FC = 0, tot = 0 ;
int MCa = 0,FCa = 0, tota = 0 ;
int MCb = 0,FCb = 0, totb = 0 ;
int MCc = 0,FCc = 0, totc = 0 ;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql =  "SELECT * FROM `Admittedstudent` WHERE 1";
   ResultSet rs = st.executeQuery(sql); 
     while(rs.next())
{    cn = cn +1;
String gender = String.valueOf(rs.getString("GENDER"));
String dep = String.valueOf(rs.getString("cycle"));
System.out.println(dep);
if(dep.equals("ODINARY TECHNICAL CYCLE"))
{
if(gender.equals("MALE")){ MC = MC + 1;}
 if(gender.equals("FEMALE")){ FC = FC+1;}   
 tot = MC + FC;
 System.out.println(MC);
}
if(dep.equals("BASIC TECHNICAL CYCLE"))
{
if(gender.equals("MALE")){ MCa = MCa+1;}
 if(gender.equals("FEMALE")){ FCa = FCa+1;}   
 tota = MCa + FCa;
}
if(dep.equals("HIGHER TECHNICAL CYCLE"))
{
if(gender.equals("MALE")){ MCb = MCb+1;}
 if(gender.equals("FEMALE")){ FCb = FCb+1;}   
 totb = MCb + FCb;
}

}
     con.close();
String mc = String.valueOf(MC); 
String fc = String.valueOf(FC); 
String TOT = String.valueOf(tot);
 String mca = String.valueOf(MCa); String fca = String.valueOf(FCa); String TOTA = String.valueOf(tota); 
 String mcb = String.valueOf(MCb); String fcb = String.valueOf(FCb); String TOTB = String.valueOf(totb);
 String mcc = String.valueOf(MCc); String fcc = String.valueOf(FCc); String TOTC = String.valueOf(totc);  
 String dep1,dep2,dep3,dep4;
 
 String Data[] = {"ORDINARY TECHNICAL CYCLE",mc,fc,TOT};
  DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
   tblModel.addRow(Data);
  String Data1[] = {"BASIC TECHNICAL CYCLE",mca,fca,TOTA};
tblModel.addRow(Data1);
  String Data2[] = {"HIGHER TECHNICAL CYCLE",mcb,fcb,TOTB};
 tblModel.addRow(Data2);

       } 
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
Connection con = null;
int cn=0, MC = 0,FC = 0, tot = 0 ;
int MCa = 0,FCa = 0, tota = 0 ;
int MCb = 0,FCb = 0, totb = 0 ;
int MCc = 0,FCc = 0, totc = 0 ;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql =  "SELECT * FROM `Admittedstudent` WHERE 1";
   ResultSet rs = st.executeQuery(sql); 
     while(rs.next())
{    cn = cn +1;
String gender = String.valueOf(rs.getString("GENDER"));
String dep = String.valueOf(rs.getString("department"));
System.out.println(dep);
if(dep.equals("CIVIL ENGINEERING"))
{
if(gender.equals("MALE")){ MC = MC + 1;}
 if(gender.equals("FEMALE")){ FC = FC+1;}   
 tot = MC + FC;
 System.out.println(MC);
}
if(dep.equals("RURAL ENGINEERING"))
{
if(gender.equals("MALE")){ MCa = MCa+1;}
 if(gender.equals("FEMALE")){ FCa = FCa+1;}   
 tota = MCa + FCa;
}
if(dep.equals("TOWN PLANNING"))
{
if(gender.equals("MALE")){ MCb = MCb+1;}
 if(gender.equals("FEMALE")){ FCb = FCb+1;}   
 totb = MCb + FCb;
}
if(dep.equals("LAND SURVEYING"))
{
if(gender.equals("MALE")){ MCc = MCc+1;}
 if(gender.equals("FEMALE")){ FCc = FCc+1;}   
 totc = MCc + FCc;
}

}
     con.close();
     
      
  
String mc = String.valueOf(MC); 
String fc = String.valueOf(FC); 
String TOT = String.valueOf(tot);
 String mca = String.valueOf(MCa); String fca = String.valueOf(FCa); String TOTA = String.valueOf(tota); 
 String mcb = String.valueOf(MCb); String fcb = String.valueOf(FCb); String TOTB = String.valueOf(totb);
 String mcc = String.valueOf(MCc); String fcc = String.valueOf(FCc); String TOTC = String.valueOf(totc);  
 String dep1,dep2,dep3,dep4;
 
 String Data[] = {"CIVIL ENGINEERING",mc,fc,TOT};
  DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
   tblModel.addRow(Data);
  String Data1[] = {"RURAL ENGINEERING",mca,fca,TOTA};
tblModel.addRow(Data1);
  String Data2[] = {"TOWN PLANNING",mcb,fcb,TOTB};
 tblModel.addRow(Data2);
 String Data3[] = {"LAND SURVEY",mcc,fcc,TOTC};
 tblModel.addRow(Data3);
       } 
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }      // TODO add your handling code here:
    // TODO add your handling code here:
                 // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
Connection con = null;
int cn=0, MC = 0,FC = 0, tot = 0 ; 
int MCa = 0,FCa = 0, tota = 0 ;
int MCb = 0,FCb = 0, totb = 0 ;
int MCc = 0,FCc = 0, totc = 0 ;
int  MC1 = 0,FC1 = 0, tot1 = 0 ;
int MC2 = 0,FC2 = 0, tot2 = 0 ;
int MC3 = 0,FC3 = 0, tot3 = 0 ;
int MC4 = 0,FC4 = 0, tot4 = 0 ;
int  MC5 = 0,FC5 = 0, tot5 = 0 ;
int MC6 = 0,FC6 = 0, tot6 = 0 ;
int MC7 = 0,FC7 = 0, tot7 = 0 ;
int MC8 = 0,FC8 = 0, tot8 = 0 ;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql =  "SELECT * FROM `Admittedstudent` WHERE 1";
   ResultSet rs = st.executeQuery(sql); 
     while(rs.next())
{    cn = cn +1;
String gender = String.valueOf(rs.getString("GENDER"));
String dep = String.valueOf(rs.getString("class"));
System.out.println(dep);
if(dep.equals("ODINARY TECHNICAL CYCLE CIVIL ENGINEERING "))
{
if(gender.equals("MALE")){ MC = MC + 1;}
 if(gender.equals("FEMALE")){ FC = FC+1;}   
 tot = MC + FC;
 System.out.println(MC);
}
if(dep.equals("ODINARY TECHNICAL CYCLE RURAL ENGINEERING"))
{
if(gender.equals("MALE")){ MCa = MCa+1;}
 if(gender.equals("FEMALE")){ FCa = FCa+1;}   
 tota = MCa + FCa;
}
if(dep.equals("ODINARY TECHNICAL CYCLE TOWN PLANNING"))
{
if(gender.equals("MALE")){ MCb = MCb+1;}
 if(gender.equals("FEMALE")){ FCb = FCb+1;}   
 totb = MCb + FCb;
}
if(dep.equals("ODINARY TECHNICAL CYCLE LAND SURVEYING"))
{
if(gender.equals("MALE")){ MCc = MCc+1;}
 if(gender.equals("FEMALE")){ FCc = FCc+1;}   
 totc = MCc + FCc;
}
if(dep.equals("BASIC TECHNICAL CYCLE CIVIL ENGINEERING"))
{
if(gender.equals("MALE")){ MC1 = MC1 + 1;}
 if(gender.equals("FEMALE")){ FC1 = FC1+1;}   
 tot1 = MC1 + FC1;
 System.out.println(MC1);
}
if(dep.equals("BASIC TECHNICAL CYCLE RURAL ENGINEERING"))
{
if(gender.equals("MALE")){ MC2 = MC2+1;}
 if(gender.equals("FEMALE")){ FC2 = FC2+1;}   
 tot2 = MC2 + FC2;
}
if(dep.equals("BASIC TECHNICAL CYCLE TOWN PLANNING"))
{
if(gender.equals("MALE")){ MC3 = MC3+1;}
 if(gender.equals("FEMALE")){ FC3 = FC3+1;}   
 tot3 = MC3 + FC3;
}
if(dep.equals("BASIC TECHNICAL CYCLE LAND SURVEYING"))
{
if(gender.equals("MALE")){ MC4 = MC4+1;}
 if(gender.equals("FEMALE")){ FC4 = FC4+1;}   
 tot4 = MC4 + FC4;
}
if(dep.equals("HIGHER TECHNICAL CYCLE CYCLE CIVIL ENGINEERING"))
{
if(gender.equals("MALE")){ MC5 = MC5 + 1;}
 if(gender.equals("FEMALE")){ FC5 = FC5+1;}   
 tot5 = MC5 + FC5;
 System.out.println(MC1);
}
if(dep.equals("HIGHER TECHNICAL CYCLE RURAL ENGINEERING"))
{
if(gender.equals("MALE")){ MC6 = MC6+1;}
 if(gender.equals("FEMALE")){ FC6 = FC6+1;}   
 tot6 = MC6 + FC6;
}
if(dep.equals("HIGHER TECHNICAL CYCLE TOWN PLANNING"))
{
if(gender.equals("MALE")){ MC7 = MC7+1;}
 if(gender.equals("FEMALE")){ FC7 = FC7+1;}   
 tot7 = MC7 + FC7;
}
if(dep.equals("HIGHER TECHNICAL CYCLE LAND SURVEYING"))
{
if(gender.equals("MALE")){ MC8 = MC8+1;}
 if(gender.equals("FEMALE")){ FC8 = FC8+1;}   
 tot8 = MC8 + FC8;
}

}
     con.close();
     
      
 
String mc = String.valueOf(MC); 
String fc = String.valueOf(FC); 
String TOT = String.valueOf(tot);
 String mca = String.valueOf(MCa); String fca = String.valueOf(FCa); String TOTA = String.valueOf(tota); 
 String mcb = String.valueOf(MCb); String fcb = String.valueOf(FCb); String TOTB = String.valueOf(totb);
 String mcc = String.valueOf(MCc); String fcc = String.valueOf(FCc); String TOTC = String.valueOf(totc);  
   
String MC11 = String.valueOf(MC1); 
String FC11 = String.valueOf(FC1); 
String TOT11 = String.valueOf(tot1);
 String MC22 = String.valueOf(MC2); String FC22 = String.valueOf(FC2); String TOT22 = String.valueOf(tot2); 
 String MC33 = String.valueOf(MC3); String FC33 = String.valueOf(FC3); String TOT33 = String.valueOf(tot3);
 String MC44 = String.valueOf(MC4); String FC44 = String.valueOf(FC4); String TOT44 = String.valueOf(tot4);
   
String MC55 = String.valueOf(MC5); 
String FC55 = String.valueOf(FC5); 
String TOT55 = String.valueOf(tot5);
 String MC66 = String.valueOf(MC6); String FC66 = String.valueOf(FC6); String TOT66 = String.valueOf(tot6); 
 String MC77 = String.valueOf(MC7); String FC77 = String.valueOf(FC7); String TOT77 = String.valueOf(tot7);
 String MC88 = String.valueOf(MC8); String FC88 = String.valueOf(FC8); String TOT88 = String.valueOf(tot8);
 
  DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
 String Data[] = {"ODINARY TECHNICAL CYCLE CIVIL ENGINEERING",mc,fc,TOT};
 
   tblModel.addRow(Data);
  String Data1[] = {"ODINARY TECHNICAL CYCLE RURAL ENGINEERING",mca,fca,TOTA};
tblModel.addRow(Data1);
  String Data2[] = {"ODINARY TECHNICAL CYCLE TOWN PLANNING",mcb,fcb,TOTB};
 tblModel.addRow(Data2);
 String Data3[] = {"ODINARY TECHNICAL CYCLE LAND SURVEY",mcc,fcc,TOTC};
 tblModel.addRow(Data3);
  String Data4[] = {"BASIC TECHNICAL CYCLE CIVIL ENGINEERING",MC11,FC11,TOT11};
  tblModel.addRow(Data4);
  String Data5[] = {"BASIC TECHNICAL CYCLE RURAL ENGINEERING",MC22,FC22,TOT22};
  tblModel.addRow(Data5);
String Data6[] = {"BASIC TECHNICAL CYCLE TOWN PLANNING",MC33,FC33,TOT33};
 tblModel.addRow(Data6);
 String Data7[] = {"BASIC TECHNICAL CYCLE LAND SURVEY",MC44,FC44,TOT44};
 tblModel.addRow(Data7);
  String Data8[] = {"HIGHER TECHNICAL CYCLE CIVIL ENGINEERING",MC55,FC55,TOT55};
  tblModel.addRow(Data8);
  String Data9[] = {"HIGHER TECHNICAL CYCLE RURAL ENGINEERING",MC66,FC66,TOT66};
  tblModel.addRow(Data9);
String Data10[] = {"HIGHER TECHNICAL CYCLE TOWN PLANNING",MC77,FC77,TOT77};
 tblModel.addRow(Data10);
 String Data11[] = {"HIGHER TECHNICAL CYCLE LAND SURVEY",MC88,FC88,TOT88};
 tblModel.addRow(Data11);
       } 
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MessageFormat header = new    MessageFormat("SCHOOL STATISTICS");     
        try
        {
        jTable1.print(JTable.PrintMode.NORMAL,header,null);
        }
        catch(Exception ex)
                { JOptionPane.showMessageDialog(null,ex);}          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statisticsofenrollement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statisticsofenrollement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statisticsofenrollement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statisticsofenrollement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statisticsofenrollement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
