/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school_management;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author frank
 */
public class VIEW_CANDIDATES extends javax.swing.JFrame {

    /**
     * Creates new form VIEW_CANDIDATES
     */
    public VIEW_CANDIDATES() {
        initComponents();
    }
    Validate_Candidate  jtRowData = new Validate_Candidate();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "SURNAME ", "DATE OF BIRTH", "PLACE OF BIRTH", "SEX", "FATHER  NAME", "MOTHER NAME", "DIVISION", "REGION", "NATIONALITY", "MARRITAL STATUS", "CHEMISTRY", "MATHS", "PHYSICS", "CONTACT", "ODINARY LEVEL", "ADVANCE LEVEL", "OLEVEL EQUIVALENT", "CYCLE", "DEPARTMENT"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("CLICK ON A CANDIDATE TO VALIDATE HIM ");

        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(572, 572, 572)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(621, 621, 621)
                        .addComponent(jButton2)))
                .addContainerGap(1664, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        Connection con = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
   String sql = "SELECT * FROM `candidate`";
   ResultSet rs = st.executeQuery(sql);
   
   while(rs.next())
           {
      String id = String.valueOf(rs.getInt("ID"));
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String date_of_birth  = String.valueOf(rs.getString("date of birth"));
String place_of_birth = String.valueOf(rs.getString("place of birth"));
String sex = String.valueOf(rs.getString("sex"));
String father_name= String.valueOf(rs.getString("father name"));
String mother_name= String.valueOf(rs.getString("mother name"));
String division= String.valueOf(rs.getString("division"));
String Region_of_Origin= String.valueOf(rs.getString("Region of Origin"));
String Nationality= String.valueOf(rs.getString("Nationality"));
String Marital_status= String.valueOf(rs.getString("Marital status"));
String chemistry= String.valueOf(rs.getString("chemistry status"));
String mathematics= String.valueOf(rs.getString("mathematic status"));
String physics= String.valueOf(rs.getString("physic status"));
String Contact= String.valueOf(rs.getInt("phone number"));
String OLSTATUS= String.valueOf(rs.getString("OL STATUS"));
String ALSTATUS= String.valueOf(rs.getString("ALSTATUS"));
String OLEQUIVALENT= String.valueOf(rs.getString("OL EQUIVALENT"));
String CYCLE= String.valueOf(rs.getString("CYCLE"));
String DEPARTMENT= String.valueOf(rs.getString("DEPARTMENT"));

String tbData[] = {id,name,Surname, date_of_birth, place_of_birth,sex,father_name,mother_name,division,Region_of_Origin,Nationality, Marital_status,chemistry,mathematics,physics,Contact,OLSTATUS,ALSTATUS,OLEQUIVALENT,CYCLE,DEPARTMENT};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);

           }
       } 
     catch(Exception ex)
     {
     JOptionPane.showMessageDialog(null,ex);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int index = jTable1.getSelectedRow();
TableModel model = jTable1.getModel();
String name = model.getValueAt(index,2).toString();
String surname = model.getValueAt(index,15).toString();
String phone = model.getValueAt(index,1).toString();
String Cycle = model.getValueAt(index,19).toString();
String Department = model.getValueAt(index,20).toString();
String GENDER = model.getValueAt(index,5).toString();

 jtRowData.setVisible(true);
 jtRowData.pack();
 jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
  jtRowData.jTextField1.setText(phone);
  jtRowData.jTextField2.setText(name);
  jtRowData.jTextField3.setText(surname);
  jtRowData.jTextField4.setText(Cycle);
  jtRowData.jTextField5.setText(Department);
  jtRowData.jTextField6.setText( Cycle +" "+ Department  );
   jtRowData.jTextField7.setText(GENDER);
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
MessageFormat header = new    MessageFormat("LIST OF CANDIDATES");     
        try
        {
        jTable1.print(JTable.PrintMode.NORMAL,header,null);
        }
        catch(Exception ex)
                { JOptionPane.showMessageDialog(null,ex);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

   
    
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIEW_CANDIDATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIEW_CANDIDATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIEW_CANDIDATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEW_CANDIDATES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEW_CANDIDATES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
