/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package school_management;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frank
 */
public class FEMALE extends javax.swing.JFrame {

    /**
     * Creates new form ClassREP
     */
    public FEMALE() {
        initComponents();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2- getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("BASIC TECHNICAL CYCLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ORDINARY TECHNICAL CYCLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HIGHER TECHNICAL CYCLE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("BASIC TECHNICAL CYCLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ORDINARY TECHNICAL CYCLE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("HIGHER TECHNICAL CYCLE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("BASIC TECHNICAL CYCLE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("ORDINARY TECHNICAL CYCLE");

        jButton9.setText("HIGHER TECHNICAL CYCLE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("BASIC TECHNICAL CYCLE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("ORDINARY TECHNICAL CYCLE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("HIGHER TECHNICAL CYCLE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel1.setText("CIVIL ENGINEERING");

        jLabel2.setText("CIVIL ENGINEERING");

        jLabel3.setText("CIVIL ENGINEERING");

        jLabel4.setText("TOWN PLANNIG");

        jLabel5.setText("TOWN PLANNIG");

        jLabel6.setText("TOWN PLANNIG");

        jLabel7.setText("RURAL ENGINEERING ");

        jLabel8.setText("LAND SURVEYING");

        jLabel9.setText("LAND SURVEYING");

        jLabel10.setText("LAND SURVEYING");

        jLabel11.setText("RURAL ENGINEERING ");

        jLabel12.setText("RURAL ENGINEERING ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SURNAME", "GENDER", "CLASS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton13.setText("PRINT");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel13.setText("                     PRESS PRINT AFTER SELECTING  A PARTICULAR CLASS TO TABLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6))
                            .addComponent(jButton4)
                            .addComponent(jButton7))
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12)))
                                .addGap(98, 98, 98))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel10)
                .addGap(270, 270, 270)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel7))
                                    .addComponent(jButton10))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(225, 225, 225))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(228, 228, 228)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel4))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jButton13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton13)
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8)
                        .addComponent(jButton7))
                    .addComponent(jButton12))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("BASIC TECHNICAL CYCLE CIVIL ENGINEERING") && gender.equals("FEMALE"))
{ System.out.println(dep);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("BASIC TECHNICAL CYCLE TOWN PLANNING") && gender.equals("FEMALE"))
{ System.out.println(dep);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }               // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("BASIC TECHNICAL CYCLE LAND SURVEYING") && gender.equals("FEMALE"))
{ System.out.println(dep);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }               // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("BASIC TECHNICAL CYCLE RURAL ENGINEERING") && gender.equals("FEMALE"))
{ System.out.println(dep);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }               // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("ODINARY TECHNICAL CYCLE TOWN PLANNING") && gender.equals("FEMALE"))
{ System.out.println(dep);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }               // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("ODINARY TECHNICAL CYCLE RURAL ENGINEERING") && gender.equals("FEMALE"))
{ System.out.println(dep);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("HIGHER TECHNICAL CYCLE CIVIL ENGINEERING") && gender.equals("FEMALE"))
{ System.out.println(Class);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("HIGHER TECHNICAL CYCLE TOWN PLANNING") && gender.equals("FEMALE"))
{ System.out.println(Class);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("HIGHER TECHNICAL CYCLE LAND SURVEYING") && gender.equals("FEMALE"))
{ System.out.println(Class);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Connection con = null;
        try 
       {
           
         Class.forName("com.mysql.cj.jdbc.Driver");
   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/school management ","root", ""); 
   Statement st = con.createStatement();
 String sql = "SELECT * FROM `Admittedstudent` WHERE 1";
 
   ResultSet rs = st.executeQuery(sql); 
  
  
  {    while(rs.next())
{
String name = String.valueOf(rs.getString("name"));
String Surname = String.valueOf(rs.getString("surname"));
String gender = String.valueOf(rs.getString("GENDER"));
String Class = String.valueOf(rs.getString("class"));
String dep = String.valueOf(rs.getString("department"));
if(Class.equals("HIGHER TECHNICAL CYCLE RURAL ENGINEERING") && gender.equals("FEMALE"))
{ System.out.println(Class);
String tbData[] = {name,Surname,gender,Class};
DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
tblModel.addRow(tbData);
}
}
      } }
   catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
MessageFormat header = new    MessageFormat("LIST OF LAND SURVEYANCE STUDENTS");     
        try
        {
        jTable1.print(JTable.PrintMode.NORMAL,header,null);
        }
        catch(Exception ex)
                { JOptionPane.showMessageDialog(null,ex);}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEMALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEMALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEMALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEMALE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEMALE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
